# Generated by Django 5.2.4 on 2025-08-26 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c183a5d8-a99b-44d2-b24c-b3dde3d2bbc9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c183a5d8-a99b-44d2-b24c-b3dde3d2bbc9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
