# Generated by Django 5.2.4 on 2025-09-06 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2bdffbe6-f0ad-4630-94ed-72ab8d5e1042'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2bdffbe6-f0ad-4630-94ed-72ab8d5e1042'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
